services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - app-uploads:/app/uploads
      - app-storage:/app/storage/worksheets

volumes:
  app-uploads:
  app-storage:
